import json

en_file = 'src/i18n/locales/en.json'
fr_file = 'src/i18n/locales/fr.json'

with open(en_file, 'r') as f:
    en = json.load(f)

with open(fr_file, 'r') as f:
    fr = json.load(f)

translations = {
    "89793412": "Changez pour garantir que les Core Web Vitals restent au vert et que la confidentialité biologique reste absolue.",
    "132652796": "Comment commencer une détox numérique ?",
    "151759638": "Oui. L’accessibilité n’est pas une fonctionnalité ; c’est notre fondement. Chaque outil que nous bâtissons est conçu pour être conforme à la norme WCAG 2.1, garantissant que votre expérience numérique inclut tous les utilisateurs, quelles que soient leurs capacités physiques.",
    "204854666": "Aucune carte de crédit requise • Offre à durée limitée",
    "210030368": "Oui. Mindful Guard est 100 % hors ligne. Il ne nécessite pas de compte, n’utilise pas de VPN et ne transmet jamais vos données d’utilisation à un serveur. Vos sessions de concentration restent sur votre appareil.",
    "300129577": "Existe-t-il des applications gratuites pour aider à réduire le temps d’écran sur Android ?",
    "303304894": "Non. Chaque kilo-octet supplémentaire que votre boutique charge est un client que vous risquez de perdre. Le poids total de FomoGen est inférieur à 2,1 Ko — plus léger qu’une seule vignette de produit. Il est conçu pour maintenir vos Core Web Vitals dans le vert.",
    "327352281": "ÉTAPE 1 — Auditez votre bande passante neuronale",
    "414714971": "Shopify en 1 clic",
    "442287699": "La « Screen Apnea » (apnée de l’écran) est la tendance à retenir son souffle ou à respirer superficiellement tout en travaillant devant un écran. Cela déclenche une réponse de stress dans le corps. Utiliser la règle 20-20-20 et faire des pauses respiratoires intentionnelles aide à atténuer cette tension physiologique.",
    "537529250": "Niveau 2",
    "585445171": "Nous utilisons une approche basée sur des principes fondamentaux pour le codage. Nos applications Shopify, comme FomoGen, ont un poids inférieur à 2,1 Ko — ce qui signifie qu’elles se chargent plus rapidement qu’une seule image de produit. Nous évitons le pistage tiers et les bibliothèques lourdes pour maintenir votre site à son meilleur niveau de performance.",
    "591389697": "Résumé de l’analyse du protocole (TL;DR)",
    "593311028": "Pro Mensuel",
    "596947137": "AppLass est 40 fois plus léger et 100 % respectueux de la confidentialité par rapport à {{competitor}}.",
    "635956964": "Expert en Design de Discipline Numérique",
    "646881068": "Technique",
    "662183526": "Les recherches montrent que 90 % de l’utilisation du téléphone se produit parce que l’appareil est à portée de main. Pendant les phases de travail profond, déplacez physiquement votre téléphone dans une autre pièce. La « friction du mouvement » est souvent suffisante pour stopper une vérification compulsive.",
    "694474582": "Puis-je afficher des données d’achat réelles ?",
    "803396386": "Slack, Email, WhatsApp. Consultez-les 3 fois par jour.",
    "817317765": "Les recherches indiquent qu’il faut en moyenne 23 minutes pour se reconcentrer sur une tâche après avoir été distrait par une notification numérique. Un temps d’écran non géré fragmente votre attention et augmente considérablement le temps nécessaire pour accomplir un travail profond et complexe.",
    "836542254": "Qu’est-ce que l’« apnée de l’écran » ?",
    "924120531": "Est-ce que ScreenVeil décharge la batterie ?",
    "959664725": "Fondation Logique",
    "996635554": "Objectif",
    "1002643001": "Politique de confidentialité de FOMOGEN - Découvrez comment nous collectons, utilisons et protégeons vos informations en tant que marchand Shopify.",
    "1058990612": "Valeur Fondamentale",
    "1068563939": "Ouvrez simplement l’application YouTube, lancez votre vidéo, puis activez ScreenVeil depuis votre volet de notifications ou le bouton flottant. Votre écran deviendra noir, mais le son continuera d’être diffusé. Pour plus de détails, consultez notre guide complet sur la <a href='/blog/youtube-background-play-2026-workaround' class='text-green-500 underline'>lecture de YouTube en arrière-plan en 2026</a>.",
    "1095322416": "Est-ce que cela fonctionnera pendant que mon téléphone est dans ma poche ?",
    "1098430986": "Oui. FomoGen ne collecte pas de données personnelles sur les acheteurs. Les notifications de preuve sociale utilisent uniquement des signaux d’achat anonymisés. Aucun cookie n’est installé sans consentement, et l’application inclut un mode respectueux de la vie privée pour les boutiques de l’UE.",
    "1196446426": "Instagram, TikTok, Actualités. Désactivez entièrement les notifications.",
    "1223793744": "Meilleure Valeur",
    "1236668061": "Conditions d’utilisation de FOMOGEN - Consultez les conditions, modalités et responsabilités des utilisateurs pour notre application Shopify.",
    "1238738112": "ÉTAPE 4 — La règle de proximité des 90 %",
    "1266769469": "La lumière bleue la nuit supprime la mélatonine. Passez votre téléphone en mode Niveaux de gris 90 minutes avant le coucher. Supprimer les couleurs vibrantes rend l’appareil psychologiquement « ennuyeux », ce qui facilite sa mise de côté.",
    "1308509519": "Gratuit / 2,99 $/mois",
    "1341826149": "Famille immédiate, appels d’urgence, alertes serveur.",
    "1460484916": "Niveau 3",
    "1524873225": "pour éteindre vos pixels. Cela supprime la tentation visuelle de « juste vérifier une vignette de plus » tout en économisant 60 % de batterie.",
    "1564281399": "MindfulGuard — Bloqueur d’applications Android gratuit | Zéro pistage",
    "1581523471": "Non. FomoGen est conçu pour les marchands non-techniques. Vous pouvez personnaliser chaque couleur, position et logique de timing via un tableau de bord visuel simple dans votre administration Shopify.",
    "1676224238": "Marchand Vérifié",
    "1713431589": "C’est un concept très intéressant, certains utilisateurs pourraient s’inquiéter de la fonction de verrouillage de leur téléphone",
    "1717698853": "Zéro Pénalité de Vitesse",
    "1752667148": "pour créer des sessions de concentration incassables. Une fois qu’une session commence, l’application vous empêche physiquement d’ouvrir les distractions. Pas de bouton « ajouter 5 minutes ». Aucun contournement.",
    "1760207165": "Politique de confidentialité de ScreenVeil - Notre approche transparente de l’efficacité AMOLED sur Android et de la collecte de données nulle.",
    "1803032920": "Débloquez l’ensemble d’outils à haute conversion utilisé par les marques Shopify d’élite. Économisez 44 % avec notre forfait annuel.",
    "1813068265": "C’est la seule façon pour Android de permettre à une application de placer une couche sur d’autres applications (comme YouTube ou Netflix). Nous l’utilisons pour dessiner le « Voile » noir pur sur votre écran. ScreenVeil ne nécessite pas d’internet, de caméra ou de permissions de contacts.",
    "1822983426": "Architecture",
    "1894361995": "Vos applications sont-elles accessibles ?",
    "1898005648": "Ne consultez pas votre téléphone pendant les 60 premières minutes de votre journée. Cela protège l’état d’« ondes alpha » de votre cerveau et vous empêche de commencer votre journée en mode réactif.",
    "1916461827": "Accédez à notre laboratoire technique directement via le module « Support » de votre tableau de bord ou contactez-nous à support@applass.com.",
    "2030437746": "Conditions d’utilisation de Mindful Guard - Compréhension de l’accord utilisateur et des règles des sessions de concentration pour notre application Android.",
    "2038694836": "Analyse Vérifiée par Experts",
    "2071323212": "Intégration",
    "-1121850533": "Conditions d’utilisation de ScreenVeil - Consultez les conditions d’utilisation de notre utilitaire de superposition pour économiser la batterie.",
    "-1433162603": "Politique de confidentialité de Mindful Guard - Découvrez notre approche zéro télémétrie et comment nous protégeons vos données de concentration hors ligne sur Android.",
    "-736624796": "Les utilisateurs perçoivent les changements en 100 ms. Si votre boutique semble « lourde », c’est un échec technique de votre pile Liquid. Ciblez ces références :",
    "-1774643589": "Le Cumulative Layout Shift empêche le phénomène frustrant du « bouton qui bouge ».",
    "-1631236339": "Garantit que le bouton « Paiement » est toujours à portée du pouce, augmentant considérablement le ROI pour les développeurs Shopify.",
    "-2103900870": "En 2026, le professionnel moyen passe plus de 11 heures par jour à interagir avec des écrans. Bien que la technologie nous ait rendus plus connectés que jamais, elle a également conduit à un « Grand Découplage » de notre attention, où les notifications constantes fragmentent notre concentration et mènent au burnout numérique.",
    "-917870": "Récupérez 2,4 h/jour",
    "-865227477": "Norme de Confidentialité",
    "-667666981": "Architecture 100 % Hors Ligne",
    "-829024535": "Stratégie de Base",
    "-1843979002": "Gestion de la Charge Cognitive",
    "-220048511": "Chaque notification est un « micro-retrait » de votre banque d’attention. Catégorisez vos applications en trois niveaux :",
    "-1190962664": "Niveau 1",
    "-1709249857": "Critique :",
    "-1830539626": "Lot :",
    "-509154927": "Supprimer :",
    "-493703280": "Votre volonté est finie. Utilisez un outil comme",
    "-125839793": "ÉTAPE 3 — Le Protocole d’Écran Éteint",
    "-1002331517": "Les recherches montrent que 90 % de l’utilisation du téléphone se produit parce que l’appareil est à portée de main. Pendant les phases de travail profond, déplacez physiquement votre téléphone dans une autre pièce. La « friction du mouvement » est souvent suffisante pour stopper une vérification compulsive.",
    "-1457270325": "ÉTAPE 5 — Gestion Circadienne de l’Affichage",
    "-821182996": "ÉTAPE 7 — Entrefer Numérique Hebdomadaire",
    "-323472625": "Verdict",
    "-1958998716": "+2,4 h de Concentration Quotidienne",
    "-1715137677": "100 % sur l’Appareil",
    "-451987097": "Payload sub-2,1 Ko",
    "-2139477035": "Métrique",
    "-1473375462": "Offre de Lancement à Durée Limitée",
    "-1303891825": "9,99 $/mois (Standard)",
    "-1339827604": "59 $/an (4,92 $/mois)",
    "-800169468": "AppLass est un studio d’ingénierie logicielle d’élite. Nous construisons des applications Shopify et des utilitaires Android haute performance qui privilégient la précision mathématique et la confidentialité des utilisateurs. Notre objectif est d’éliminer le « gonflement » numérique et de vous aider à reconquérir votre performance.",
    "-1956020024": "Vous pouvez contacter notre laboratoire d’ingénierie directement à support@applass.com. Parce que nos outils sont conçus pour la précision, we offer direct developer support to ensure your integration is seamless.",
    "-332456347": "ScreenVeil est une application Android gratuite avec plus de 10 000 téléchargements et une note de 4,4 étoiles. Elle superpose une couche de noir pur sur les écrans AMOLED/OLED pour que les pixels s’éteignent physiquement, économisant ainsi 60 % de batterie pendant que vous écoutez YouTube, des podcasts ou tout autre contenu audio.",
    "-196557209": "Comment lire YouTube en arrière-plan comme avec Premium ?",
    "-459686945": "Pourquoi ScreenVeil a-t-il besoin de la permission « Affichage par-dessus d’autres applications » ?",
    "-430047171": "Oui. ScreenVeil inclut une fonction « Pocket Guard » qui bloque à toutes les entrées tactiles lorsque le voile est actif. Cela empêche les sauts accidentels, les pauses ou les « appels fantômes » lorsque votre téléphone est dans votre poche ou votre sac.",
    "-1017546983": "Non. ScreenVeil est conçu pour une efficacité extrême. Il utilise 0 % de CPU lorsqu’il est actif. En éteignant les pixels sur les écrans AMOLED, il économise réellement jusqu’à 60 % de la consommation d’énergie totale de votre appareil lors de la lecture vidéo.",
    "-45306900": "ScreenVeil ne collecte aucune donnée personnelle. Elle ne nécessite aucun accès à Internet et ne contient aucun SDK d’analyse tiers. La seule permission dont elle a besoin est « Affichage par-dessus d’autres applications » — rien de plus.",
    "-76087506": "FomoGen est un moteur de preuve sociale d’élite pour Shopify. Il coordonne 9 modules distincts d’urgence et de rareté — incluant les notifications d’achat, la logique d’intention de sortie et la télémétrie des stocks — pour maximiser les performances de conversion.",
    "-1473507405": "Vitals regroupe plus de 40 fonctionnalités que la plupart des marchands n’utilisent jamais, ajoutant un poids de script massif. Nudgify s’appuie sur le rendu cloud avec une latence notable. FomoGen vous offre les 5 outils aux taux de conversion les plus élevés dans un seul script optimisé pour la vitesse.",
    "-1054639414": "Oui. FomoGen s’installe via le système App Block de Shopify et est compatible avec tous les thèmes Online Store 2.0, incluant Dawn, Refresh, Sense et tous les thèmes payants majeurs. Aucune modification de code requise.",
    "-146100642": "Oui. Alors que de nombreuses applications nécessitent des abonnements, des utilitaires comme Mindful Guard offrent un blocage puissant au niveau du système gratuitement. De plus, les outils intégrés comme le « Bien-être numérique » d’Android offrent un suivi de base, bien qu’ils soient souvent plus faciles à contourner que les applications de concentration dédiées.",
    "-921658368": "Pourquoi ai-je besoin d’un blocage d’application plutôt que de ma seule volonté ?",
    "-744972130": "Les algorithmes des médias sociaux sont conçus par des milliers d’ingénieurs pour vous faire défiler sans fin. La volonté est une ressource finie qui s’épuise tout au long de la journée. Utiliser un blocage « dur » comme Mindful Guard élimine entièrement le processus de prise de décision, protégeant votre concentration automatiquement.",
    "-820156952": "Commencez petit. Débutez par l’étape 6 de notre guide : La Première Heure Analogique. Une fois que vous aurez maîtrisé les 60 premières minutes de votre journée sans écran, passez à l’étape 1 (audit des notifications) et enfin à l’étape 7 (l’entrefer numérique hebdomadaire).",
    "-387868496": "Précision Mathématique",
    "-411196376": "Design.",
    "-131694621": "Arrêtez de laisser les logiciels encombrants ralentir votre croissance. Nous concevons des outils mobiles et Shopify de premier plan, guidés par une précision basée sur des principes fondamentaux.",
    "-293341793": "Le mode strict est conçu pour être permanent pour la durée que vous avez définie. Il n’y a aucun « déverrouillage d’urgence » par conception. À utiliser avec intention.",
    "-1984738556": "Le module de progression surveille l’objet panier Shopify en temps réel. À mesure que l’écart se réduit entre l’état actuel du panier et le jalon cible, l’indicateur visuel fournit un retour cinétique, déclenchant l’« effet de gradient de but » dans la psychologie du consommateur.",
    "-759124288": "Fermer",
    "-453911714": "ScreenVeil est complètement gratuit. Nous ne vendons pas vos données, nous n’affichons pas de publicités et nous ne demandons aucune permission autre que la superposition d’affichage.",
    "-1919835829": "GOOGLE PLAY",
    "-1126278391": "Lancer l’essai"
}

fr.update(translations)

with open(fr_file, 'w') as f:
    json.dump(fr, f, indent=2, ensure_ascii=False)

print('✅ Successfully updated fr.json with missing translations.')
